### ISSUE TITLE
Deploy, github.io or surge.sh

### ISSUE THREAD

**Issue by MichaelDimmitt** [ttamnam/rgbColorGame#2]
1) https://docs.github.com/en/free-pro-team@latest/github/working-with-github-pages/configuring-a-publishing-source-for-your-github-pages-site
2) https://surge.sh/

**Comment by chinmaym07** [comment]
Hey @MichaelDimmitt  Can I try this?

**Comment by MichaelDimmitt** [comment]
This is @ttamnam 's project

@chinmaym07 , I say go for it; usually to get github pages working you need to be the owner of the repository which is @ttamnam . You should be able to deploy to surge.sh. I would just post the link in a future comment after surge.sh deploy is successfull. 

and/or submit a pr to the readme with the link added.

**Comment by ttamnam** [comment]
@MichaelDimmitt @chinmaym07 
Yes. Go for it! I usually just go to [https://ttamnam.github.io/rgbColorGame/](url) to run the app. Do you want me to configure the settings so you can publish it on a different web page?

**Comment by MichaelDimmitt** [comment]
@ttamnam , has got it working for github pages, 👍
someone just needs to add the link to the readme

https://ttamnam.github.io/rgbColorGame/

I could have sworn it was not working when I checked a week ago
